### ISSUE TITLE
Issue with port being in use when trying to run with docker

### ISSUE THREAD

**Issue by bedazzlinghex** [maurermj08/efetch#14]
I have tried to build a docker image using your quick installer on a ubuntu:14.04 image. It seems to work when you just type "efetch" without any parameters on the command line, however I get a "connection refused" from the webserver. When I try to specify the address as seen below and open up the port in docker I get an error, also seen below. Any ideas?

It does not mather which port i specify, I get the same error message.

## Run command
docker run -d --name=efetch -p 8080:8080 -ti efetch:0.4 efetch --address 192.168.99.104 --elastic 192.168.99.101:9200

## Error
$ docker logs -f efetch
INFO:root:Plugin YAML file updated
**ERROR:Rocket.Errors.Port8080:Socket 192.168.99.104:8080 in use by other process and it won't share.
**INFO:Rocket:Starting** Rocket 1.2.4
**INFO:Rocket:Listening** on sockets: 192.168.99.104:8080
**WARNING:Rocket.Errors.Port8080:Listener** started when not ready.**

NB! There should not be anything in used on that port, so the error is strange. Something with the webserver used by efetch?

**Comment by maurermj08** [comment]
The most common cause for this error is the **efetch** server failed to shutdown properly or another process is using that port. 

Are there any other **efetch** processes running:

```
ps aux | grep efetch
```

If so kill them using kill -9 $pid

By default efetch uses port 8080, a rather common default port for web servers. So if another process is using that port just use the -p option with a different port. 

```
efetch -p 8181
```

To check what process is using 8080 use:

```
sudo netstat -nlp | grep :8080
```

**Note:** I have not tested efetch in docker yet, but it should be the same.
