### ISSUE TITLE
Broken Dependencies - Python

### ISSUE THREAD

**Issue by Syrkadian** [maurermj08/efetch#20]
The install breaks when running this command from the Dockerfile:
RUN apt-get -y install python-plaso python-dev python-setuptools unoconv libpff libpff-python zlib1g-dev libjpeg-dev libtiff5-dev python-pip

It seems to need updating

**Comment by maurermj08** [comment]
I will take a look as soon as I get a chance. It has been a while since I have worked on this project, so I think it needs some updates.

**Comment by Syrkadian** [comment]
It’s all good. I updated the Dockerfile and got everything installed I think. But when the code tries to run, it gets a bunch of exceptions. I’ll upload the updated Dockerfile in my form if you want it. Thank you for responding.
